### ISSUE TITLE
Protocol: Implement pipelining?

### ISSUE THREAD

**Issue by Szperak** [thinkofdeath/steven#31]
I didn't found any 
https://github.com/thinkofdeath/steven/search?q=pipeline
or even
https://github.com/thinkofdeath/steven/search?q=pipe

**Comment by yawkat** [comment]
Why?

**Comment by Szperak** [comment]
What if mojang would add next step in the protocol as it was with compression?

**Comment by yawkat** [comment]
add it https://github.com/thinkofdeath/steven/blob/master/protocol/connection.go

**Comment by Szperak** [comment]
So can I rewrite it to be pipeline?

**Comment by yawkat** [comment]
no, why

**Comment by Szperak** [comment]
Ok, I see, pipelining is more necessary you're when writing proxy.
