### ISSUE TITLE
steven: panic when joining custom server

### ISSUE THREAD

**Issue by Szperak** [thinkofdeath/steven#38]
https://gist.github.com/Szperak/750e2225f98c40a57c52

Probably it is caused by 1.8 Player List packet not being sent. (Player NPCs on map)
Vanilla client (1.8.6) is not crashing in such conditions.
https://github.com/thinkofdeath/steven/blob/6a200d028363cd28a6c5054530991fdd2edd5ea2/entitymodels.go#L153
EDIT: Why "custom" server? The server is using slightly modified LilyPad.

**Comment by thinkofdeath** [comment]
Without the skin I can't display a model, this isn't valid from the protocol and causes weird issues in vanilla too. The correct way is to display on the player list + spawn the player + remove the list entry. That works fine in steven
