### ISSUE TITLE
steven: not rendering bossbar

### ISSUE THREAD

**Issue by ApfelUser** [thinkofdeath/steven#40]
Steven is not rendering ender- and witherbars.

**Steven:**

![steven_enderbar](https://cloud.githubusercontent.com/assets/7549136/7898355/c5b1c802-06fd-11e5-9a1e-9782cbe2db10.jpg)

versus **Minecraft:**

![minecraft_enderbar](https://cloud.githubusercontent.com/assets/7549136/7898358/d5a5c7a4-06fd-11e5-82c6-09053307be2f.png)

**Comment by thinkofdeath** [comment]
Merged into #55
