### ISSUE TITLE
steven: not rendering flowers and tall grass

### ISSUE THREAD

**Issue by ApfelUser** [thinkofdeath/steven#41]
Steven is not rendering flowers and tall grass.

**Steven:**

![steven_flowers](https://cloud.githubusercontent.com/assets/7549136/7898380/6804881a-06fe-11e5-807c-03d496bfc98a.jpg)

versus **Minecraft:**

![minecraft_flowers](https://cloud.githubusercontent.com/assets/7549136/7898383/758f6ac2-06fe-11e5-8fe7-7bbbb7bec261.png)

**Comment by thinkofdeath** [comment]
Merged into #54
