### ISSUE TITLE
steven: steven is rendering invisible NPC's

### ISSUE THREAD

**Issue by ApfelUser** [thinkofdeath/steven#42]
Steven is rendering invisible NPC's.

  * **Left / Red =** Blaze
  * **Mid / Grey =** Wither
  * **Right / Beige =** Villager

**Steven:**

![steven_ncps](https://cloud.githubusercontent.com/assets/7549136/7898385/ac28e3ba-06fe-11e5-9d7b-b75b53fc05d6.jpg)

versus **Minecraft:**

![minecraft_ncps](https://cloud.githubusercontent.com/assets/7549136/7898389/b769977e-06fe-11e5-97b9-517d6f4dc9a7.png)

**Comment by thinkofdeath** [comment]
Merged into #55
