### ISSUE TITLE
steven: not rendering scoreboard

### ISSUE THREAD

**Issue by ApfelUser** [thinkofdeath/steven#43]
Steven is not rendering the scoreboard.

**Steven:**

![steven_scoreboard](https://cloud.githubusercontent.com/assets/7549136/7898410/45c6de32-06ff-11e5-94e6-4b660d88c9ba.jpg)

versus **Minecraft:**

![minecraft_scoreboard](https://cloud.githubusercontent.com/assets/7549136/7898411/5090640a-06ff-11e5-82c1-a0118d0cc402.png)

**Comment by thinkofdeath** [comment]
Merged into #55
