### ISSUE TITLE
steven: not rendering player head items in a slot

### ISSUE THREAD

**Issue by ApfelUser** [thinkofdeath/steven#48]
Steven is not rendering player head items in a slot.

**Steven:**

![steven_head](https://cloud.githubusercontent.com/assets/7549136/7899630/15f8998a-072b-11e5-8a58-76d8dd6eee38.jpg)

versus **Minecraft:**

![minecraft_head](https://cloud.githubusercontent.com/assets/7549136/7899629/13e93e4c-072b-11e5-9fda-4a0efed5fcb9.jpg)

**Comment by thinkofdeath** [comment]
Merged into #55
