### ISSUE TITLE
1.8.8 Support :0

### ISSUE THREAD

**Issue by Samistine** [thinkofdeath/steven#71]
What happened to supporting stable minecraft versions :(

**Comment by thinkofdeath** [comment]
Decided snapshots were more fun and then had to stop working on the project

**Comment by ApfelUser** [comment]
So is this dead, or just temporarily inactive?

**Comment by thinkofdeath** [comment]
@ApfelUser Uni work took over sadly. If I start getting more free time i'll most likely return to this
